src/objects/Convert_Notes_to_ContentNotes_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls when and how certain notes are converted to enhanced notes.</description>
    <fields>
        <fullName>Convert_Private_Notes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Enable this option to convert private notes to enhanced notes. Please consider your company&apos;s regulatory and security policies before enabling this option as it may expose data to new audiences.</description>
        <inlineHelpText>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Please consider your company&apos;s regulatory and security policies before enabling this option as it may expose data to new audiences.</inlineHelpText>
        <label>Convert Private Notes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Convert_in_Near_Real_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables &apos;after insert&apos; trigger on Note that enqueues job to convert into ContentNotes in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Notes&apos; option is enabled then deletes in separate transaction too.</description>
        <inlineHelpText>Enables &apos;after insert&apos; trigger on Note that enqueues job to convert into ContentNotes in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Notes&apos; option is enabled then deletes in separate transaction too.</inlineHelpText>
        <label>Convert in Near Real Time?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delete_Note_Once_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked then conversion process will delete the original Note once successfully converted to ContentNote. You may want to delete them to save storage space in your org.</description>
        <inlineHelpText>When checked then conversion process will delete the original Note once successfully converted to ContentNote. You may want to delete them to save storage space in your org.</inlineHelpText>
        <label>Delete Note Once Converted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Private_Notes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Enable this option to share converted private notes with their parent record and to anyone who has access to the parent record.</description>
        <inlineHelpText>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Enable this option to share converted private notes with their parent record and to anyone who has access to the parent record.</inlineHelpText>
        <label>Share Private Notes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Type__c</fullName>
        <defaultValue>&quot;V&quot;</defaultValue>
        <description>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</description>
        <inlineHelpText>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</inlineHelpText>
        <label>Share Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <defaultValue>&quot;InternalUsers&quot;</defaultValue>
        <description>The ContentDocumentLink.Visibility value to use for converted files. For any user with permission to view the file, this further controls which set of users can actually see it.
&quot;InternalUsers&quot; = only internal users with permission to view file
&quot;AllUsers&quot; = all users, including community users, with permission to view file</description>
        <inlineHelpText>The ContentDocumentLink.Visibility value to use for converted files.
&quot;InternalUsers&quot; = only internal users with permission to view file
&quot;AllUsers&quot; = all users, including community users, with permission to view file</inlineHelpText>
        <label>Visibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Convert Notes to ContentNotes Settings</label>
</CustomObject>

src/classes/ConvertNotesSettingsControllerTest.cls
/**
 * Developed by Doug Ayers (douglascayers.com)
 */
@isTest
private class ConvertNotesSettingsControllerTest {

    @isTest
    static void test_communities_enabled() {

        Test.startTest();

        ConvertNotesSettingsController controller = new ConvertNotesSettingsController();

        Boolean isCommunitiesEnabled = controller.isCommunitiesEnabled;

        Test.stopTest();

        System.assertEquals( Schema.getGlobalDescribe().containsKey( 'Network' ), isCommunitiesEnabled );

    }

    @isTest
    static void test_save_new_settings() {

        Convert_Notes_to_ContentNotes_Settings__c settings = Convert_Notes_to_ContentNotes_Settings__c.getOrgDefaults();
        settings.Share_Type__c = 'I';
        settings.Visibility__c = 'AllUsers';
        settings.Convert_in_Near_Real_Time__c = false;
        settings.Delete_Note_Once_Converted__c = true;
        settings.Convert_Private_Notes__c = true;
        settings.Share_Private_Notes__c = true;

        Test.startTest();

        ConvertNotesSettingsController controller = new ConvertNotesSettingsController();

        controller.settings = settings;
        controller.convertAndSharePrivateNotes = 'yes_convert_yes_share';

        controller.save();

        Test.stopTest();

        System.assertEquals( true, controller.success );
        System.assert( controller.message.containsIgnoreCase( 'Settings saved successfully' ) );

    }

    @isTest
    static void test_update_existing_settings() {

        Convert_Notes_to_ContentNotes_Settings__c settings = Convert_Notes_to_ContentNotes_Settings__c.getOrgDefaults();
        settings.Share_Type__c = 'I';
        settings.Visibility__c = 'AllUsers';
        settings.Convert_in_Near_Real_Time__c = false;
        settings.Delete_Note_Once_Converted__c = true;
        settings.Convert_Private_Notes__c = true;
        settings.Share_Private_Notes__c = true;

        upsert settings;

        Test.startTest();

        ConvertNotesSettingsController controller = new ConvertNotesSettingsController();

        controller.settings = settings;

        controller.save();

        Test.stopTest();

        System.assertEquals( true, controller.success );
        System.assert( controller.message.containsIgnoreCase( 'Settings saved successfully' ) );

    }

    @isTest
    static void test_save_error() {

        Convert_Notes_to_ContentNotes_Settings__c settings = Convert_Notes_to_ContentNotes_Settings__c.getOrgDefaults();
        settings.Share_Type__c = 'I';
        settings.Visibility__c = 'AllUsers';
        settings.Convert_in_Near_Real_Time__c = false;
        settings.Delete_Note_Once_Converted__c = true;
        settings.Convert_Private_Notes__c = true;
        settings.Share_Private_Notes__c = true;

        upsert settings;

        Test.startTest();

        ConvertNotesSettingsController controller = new ConvertNotesSettingsController();

        controller.settings = settings;

        // leave fields blank, cause validation errors
        controller.settings.visibility__c = null;

        controller.save();

        System.assertEquals( false, controller.success );
        System.assert( controller.message.containsIgnoreCase( 'Please answer all questions' ) );

        // fix validation error
        controller.settings.visibility__c = 'AllUsers';

        delete settings; // will cause exception on save because ID field is still populated on controller's reference

        controller.save();

        Test.stopTest();

        System.assertEquals( false, controller.success );

    }

    @isTest
    static void test_infer_convert_and_share_private_notes() {

        Convert_Notes_to_ContentNotes_Settings__c settings = new Convert_Notes_to_ContentNotes_Settings__c();

        ConvertNotesSettingsController controller = new ConvertNotesSettingsController();

        Test.startTest();

        settings.Convert_Private_Notes__c = true;
        settings.Share_Private_Notes__c = true;
        System.assertEquals( 'yes_convert_yes_share', controller.inferConvertAndSharePrivateNotes( settings ) );

        settings.Convert_Private_Notes__c = true;
        settings.Share_Private_Notes__c = false;
        System.assertEquals( 'yes_convert_no_share', controller.inferConvertAndSharePrivateNotes( settings ) );

        settings.Convert_Private_Notes__c = false;
        settings.Share_Private_Notes__c = true; // ignored when convert is false
        System.assertEquals( 'no_convert_no_share', controller.inferConvertAndSharePrivateNotes( settings ) );

        settings.Convert_Private_Notes__c = false;
        settings.Share_Private_Notes__c = false; // ignored when convert is false
        System.assertEquals( 'no_convert_no_share', controller.inferConvertAndSharePrivateNotes( settings ) );

        Test.stopTest();

    }

    @isTest
    static void test_apply_convert_and_share_private_notes() {

        Convert_Notes_to_ContentNotes_Settings__c settings = new Convert_Notes_to_ContentNotes_Settings__c();

        ConvertNotesSettingsController controller = new ConvertNotesSettingsController();

        Test.startTest();

        controller.applyConvertAndSharePrivateNotes( settings, 'yes_convert_yes_share' );
        System.assertEquals( true, settings.Convert_Private_Notes__c );
        System.assertEquals( true, settings.Share_Private_Notes__c );

        controller.applyConvertAndSharePrivateNotes( settings, 'yes_convert_no_share' );
        System.assertEquals( true, settings.Convert_Private_Notes__c );
        System.assertEquals( false, settings.Share_Private_Notes__c );

        controller.applyConvertAndSharePrivateNotes( settings, 'no_convert_yes_share' );
        System.assertEquals( false, settings.Convert_Private_Notes__c );
        System.assertEquals( false, settings.Share_Private_Notes__c ); // always false if convert is false

        controller.applyConvertAndSharePrivateNotes( settings, 'no_convert_no_share' );
        System.assertEquals( false, settings.Convert_Private_Notes__c );
        System.assertEquals( false, settings.Share_Private_Notes__c ); // always false if convert is false

        settings.Convert_Private_Notes__c = true;
        settings.Share_Private_Notes__c = true;
        controller.applyConvertAndSharePrivateNotes( settings, 'gibberish' );
        System.assertEquals( false, settings.Convert_Private_Notes__c ); // always false for unrecognized values
        System.assertEquals( false, settings.Share_Private_Notes__c ); // always false for unrecognized values

        Test.stopTest();

    }

}