src/objects/Convert_Notes_to_ContentNotes_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls when and how certain notes are converted to enhanced notes.</description>
    <fields>
        <fullName>Convert_Private_Notes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Enable this option to convert private notes to enhanced notes. Please consider your company&apos;s regulatory and security policies before enabling this option as it may expose data to new audiences.</description>
        <inlineHelpText>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Please consider your company&apos;s regulatory and security policies before enabling this option as it may expose data to new audiences.</inlineHelpText>
        <label>Convert Private Notes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delete_Note_Once_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked then conversion process will delete the original Note once successfully converted to ContentNote. You may want to delete them to save storage space in your org.</description>
        <inlineHelpText>When checked then conversion process will delete the original Note once successfully converted to ContentNote. You may want to delete them to save storage space in your org.</inlineHelpText>
        <label>Delete Note Once Converted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Private_Notes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Enable this option to share converted private notes with their parent record and to anyone who has access to the parent record.</description>
        <inlineHelpText>Notes have &apos;IsPrivate&apos; field that limits access to owner and admins. ContentNotes related to records are not private. Enable this option to share converted private notes with their parent record and to anyone who has access to the parent record.</inlineHelpText>
        <label>Share Private Notes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Type__c</fullName>
        <defaultValue>&quot;V&quot;</defaultValue>
        <description>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</description>
        <inlineHelpText>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</inlineHelpText>
        <label>Share Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <defaultValue>&quot;InternalUsers&quot;</defaultValue>
        <description>The ContentDocumentLink.Visibility value to use for converted files. For any user with permission to view the file, this further controls which set of users can actually see it.
&quot;InternalUsers&quot; = only internal users with permission to view file
&quot;AllUsers&quot; = all users, including community users, with permission to view file</description>
        <inlineHelpText>The ContentDocumentLink.Visibility value to use for converted files.
&quot;InternalUsers&quot; = only internal users with permission to view file
&quot;AllUsers&quot; = all users, including community users, with permission to view file</inlineHelpText>
        <label>Visibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Convert Notes to ContentNotes Settings</label>
</CustomObject>

src/classes/ConvertNotesSettingsController.cls
/**
 * Developed by Doug Ayers (douglascayers.com)
 */
public with sharing class ConvertNotesSettingsController {

    public Convert_Notes_to_ContentNotes_Settings__c settings { get; set; }

    // this option combines two setting fields for whether or not to
    // actually convert private notes, and if yes, how to share them.
    // based on the submitted value then settings.Convert_Private_Notes__c and settings.Share_Private_Notes__c
    // will be assigned their true/false values.
    // this allows us to have one radio button on the vf page even though stored in two fields in database
    public String convertAndSharePrivateNotes { get; set; }

    public String message { get; set; }

    public Boolean success { get; set; }

    public Boolean isCommunitiesEnabled {
        get {
            return Schema.getGlobalDescribe().containsKey( 'Network' );
        }
    }

    public ConvertNotesSettingsController() {

        this.settings = Convert_Notes_to_ContentNotes_Settings__c.getOrgDefaults();
        this.convertAndSharePrivateNotes = inferConvertAndSharePrivateNotes( this.settings );

    }

    public void save() {

        SavePoint sp = Database.setSavePoint();

        ID originalId = this.settings.id;

        try {

            applyConvertAndSharePrivateNotes( this.settings, this.convertAndSharePrivateNotes );

            if ( settings.Delete_Note_Once_Converted__c == null ||
                 settings.Convert_Private_Notes__c == null ||
                 settings.Share_Private_Notes__c == null ||
                 settings.Share_Type__c == null ||
                 settings.Visibility__c == null
            ) {

                this.success = false;
                this.message = 'Please answer all questions to configure conversion options.';

            } else {

                upsert this.settings;

                // refresh any values set on insert
                this.settings = Convert_Notes_to_ContentNotes_Settings__c.getOrgDefaults();

                this.message = 'Settings saved successfully!';
                this.success = true;

            }

        } catch ( Exception e ) {

            System.debug( LoggingLevel.ERROR, e.getMessage() + ' : ' + e.getStackTraceString() );

            Database.rollback( sp );

            this.settings.id = originalId;

            this.message = e.getMessage();
            this.success = false;

        }

    }

    /**
     * Based on Convert_Private_Notes__c and Share_Private_Notes__c will return one of three values:
     *  1. yes_convert_yes_share
     *  2. yes_convert_no_share
     *  3. no_convert_no_share
     */
    @TestVisible
    private String inferConvertAndSharePrivateNotes( Convert_Notes_to_ContentNotes_Settings__c settings ) {

        String value = 'no_convert_no_share';

        if ( settings.Convert_Private_Notes__c ) {
            if ( settings.Share_Private_Notes__c ) {
                value = 'yes_convert_yes_share';
            } else {
                value = 'yes_convert_no_share';
            }
        }

        return value;
    }

    /**
     * Based on the value of the 'convertAndSharePrivateNotes' string this method
     * assigns true/false to the setting's Convert_Private_Notes__c and Share_Private_Notes__c fields.
     */
    @TestVisible
    private void applyConvertAndSharePrivateNotes( Convert_Notes_to_ContentNotes_Settings__c settings, String convertAndSharePrivateNotes ) {

        if ( convertAndSharePrivateNotes == 'yes_convert_yes_share' ) {
            settings.Convert_Private_Notes__c = true;
            settings.Share_Private_Notes__c = true;
        } else if ( convertAndSharePrivateNotes == 'yes_convert_no_share' ) {
            settings.Convert_Private_Notes__c = true;
            settings.Share_Private_Notes__c = false;
        } else {
            settings.Convert_Private_Notes__c = false;
            settings.Share_Private_Notes__c = false;
        }

    }

}